services:
  - type: web
    name: exoera-app
    env: php
    plan: free
    buildCommand: ""
    startCommand: ""
    rootDir: Public
    envVars:
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_NAME
        value: YOUR_DB_NAME
      - key: DB_USER
        value: YOUR_DB_USER
      - key: DB_PASS
        value: YOUR_DB_PASSWORD
